# Site settings
theme: jekyll-theme-slate # Specify the Jekyll theme you want to use
title: Karthick Jayaraman
description:
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://karthick-840.github.io/" # the base hostname & protocol for your site

# Collections
collections:
  collection_name:
    output: true

header_pages:
  - _pages/about.md
  - _pages/contact.md
  - _pages/portfolio.md
  


# Build settings
build_settings:
  markdown: kramdown
  plugins:
  - jekyll-feed # Enables automatic generation of an Atom feed
  github_pages:
    jekyll_version: 3.9.0 # Specify the Jekyll version to use
